### ISSUE TITLE
aggregated test phase input (u, i) and separated training input (u, i) mismatch

### ISSUE THREAD

**Issue by nmrenyi** [nmrenyi/ReChorus#4]
1. training and testing #user and #item mismatch, leading to error when loading model onto current dataset inited model. It shows that not all data clusters owns all users and items (is it ok?)
2. training and testing user id and item id mismatch, leading to user and item embedding mismatching.

**Comment by Xiaoyu-SZ** [comment]
1.我也在思考这个问题，但神经网络分块的方法不能保证每块都包含每一个用户的数据。即使是随机分块，对于数目较少的用户也很难保证这一点。因此我觉得我们可能还是需要优化模块融合。

2.rechorus的数据集划分：对于每个user，抽出一个pair加入leave，一个pair加入dev，一个加入test，这时leave dev test的数目都是user_num
剩余的数据+leave形成train
这样保证 train dev test都包含了所有user

但在cluster中，每个user的（user,item）数可能小于3
这样会导致抽取每个user各一份加入leave,test后,数据集中某些user的数据被分配完了，只能把剩下的user各一份分配给dev
最终导致test和dev集长度不一致

**Comment by nmrenyi** [comment]
第1个问题，确实无论是哪种clustering方法，都可能没法保证每个cluster都拥有所有的user和item，这个问题是不能避免的，之后会由我修改代码，增强其鲁棒性来适应这个情况。

**Comment by nmrenyi** [comment]
> 1.我也在思考这个问题，但神经网络分块的方法不能保证每块都包含每一个用户的数据。即使是随机分块，对于数目较少的用户也很难保证这一点。因此我觉得我们可能还是需要优化模块融合。
> 
> 2.rechorus的数据集划分：对于每个user，抽出一个pair加入leave，一个pair加入dev，一个加入test，这时leave dev test的数目都是user_num 剩余的数据+leave形成train 这样保证 train dev test都包含了所有user
> 
> 但在cluster中，每个user的（user,item）数可能小于3 这样会导致抽取每个user各一份加入leave,test后,数据集中某些user的数据被分配完了，只能把剩下的user各一份分配给dev 最终导致test和dev集长度不一致

关于第2个问题，我想确认一点，clustering的数据集划分操作，是在ReChorus对数据集做重编号(reindexing)（把userID字符串转换为int）之前还是之后？如果在reindexing前做clustering，可能就会导致不同cluster中同一个user(or item)的embedding编号不同，这会导致对整体模型评测时，我们输入统一的item编号时，对应到的item其实并不一样。

**Comment by Xiaoyu-SZ** [comment]
之前。在random_clusteer中只做了sample和reset_index，reset_index重编的是表格的行号码，行号是一种pands.dataFrame的特性（例如抽出2，4，5三行，重新编行号为1，2，3），而不是user/item的id

**Comment by nmrenyi** [comment]
我不理解。看了一下你的cluster代码，我认为你做的cluster操作，是在重编号（把userID字符串转换为int）之前，如下面附上的`ann-machineunlearning/main.py`中的第[27](https://git.tsinghua.edu.cn/ann-prj/ann-machineunlearning/-/blob/master/main.py#L27)行-第[30](https://git.tsinghua.edu.cn/ann-prj/ann-machineunlearning/-/blob/master/main.py#L30)行所示。你说的reset_index是对dataframe的行号做重设，我说的是对原始数据集中user或item的ID字符串做编号。
```
df = data_parse(RAW_PATH,DATA_FILE,META_FILE)
train_df,dev_df,test_df=data_split(df,RAW_PATH,NEG_ITEMS)
clusters = random_clustering(K,train_df)
split_and_save(clusters)
```

**Comment by Xiaoyu-SZ** [comment]
你是对的，我写bug了（。）
我改一下，把编号移动到data_parse

**Comment by Xiaoyu-SZ** [comment]
moved
    uids = sorted(out_df['user_id'].unique())
    user2id = dict(zip(uids, range(1, len(uids) + 1)))
    iids = sorted(out_df['item_id'].unique())
    item2id = dict(zip(iids, range(1, len(iids) + 1)))

    out_df['user_id'] = out_df['user_id'].apply(lambda x: user2id[x])
    out_df['item_id'] = out_df['item_id'].apply(lambda x: item2id[x])
into data_parse

**Comment by nmrenyi** [comment]
> moved uids = sorted(out_df['user_id'].unique()) user2id = dict(zip(uids, range(1, len(uids) + 1))) iids = sorted(out_df['item_id'].unique()) item2id = dict(zip(iids, range(1, len(iids) + 1)))
> 
> ```
> out_df['user_id'] = out_df['user_id'].apply(lambda x: user2id[x])
> out_df['item_id'] = out_df['item_id'].apply(lambda x: item2id[x])
> ```
> 
> into data_parse

我看了你做的改动，但是感觉你这次commit前后，代码运行的结果不会有变化？因为`data_split`和`data_parse`是前后紧跟的两个步骤。

**Comment by Xiaoyu-SZ** [comment]
首先进行data_parse和data_split，把原数据分成  train,dev和test
然后做cluster，把train分成k个cluster
然后对k个cluster分别做data_split，拆分成train,dev和test
挪到sparse后，分配id只进行了一次

**Comment by Xiaoyu-SZ** [comment]
最后的一句的意思是
原本分配id的代码在data_split，所以会重复标号
现在放在data_sparse，只在最开始的时候分配一次id

**Comment by nmrenyi** [comment]
可不可以这样理解：
之前的数据划分做法，是先做clustering，然后再分配ID。这样可能会导致同一个item在不同的cluster中编号不同，是不对的。
现在的数据划分做法，是先分配ID，然后再做clustering。这样做的话同一个item在不同的cluster中编号是相同的，是正确的。

**Comment by nmrenyi** [comment]
原来的流程中，reindexing 是在data split开头的。data split其实调用了1 + shard次，会导致每一次shard时，都进行reindexing，会出问题。现在把redinexing放在读数据后，在data split前，不包含在data split中。这样整个过程只在读数据之后进行一次reindexing，保证不同cluster间reindexing编号的一致性。

zxy explained to renyi on 20211129 after THUR weekly presentation
